Probes values support
sighupio/gatekeeper-policy-manager pull request #1274
Opened 2024-12-17 17:33 UTC by viliger18

Need it in my environment and rather not store a local copy of the chart.
Nothing fancy just support for liveness and readiness values in values.yaml

2024-12-18 10:56 UTC, ralgozino requested changes
Hello!

Thanks for the PR. I don't think I understand though. We already had the probes in the chart as you can see in the diff, but they were hardcoded and not configurable in the `values`.

What is it that you need in your environment?

2024-12-18 10:56 UTC, ralgozino commented on chart/values.yaml
> +    path: /ready
we don't have a /ready endpoint. In the plain manifests we are using `/health` for both probes

```suggestion
    path: /health
```

2024-12-18 10:56 UTC, ralgozino commented on chart/values.yaml
> +    port: 8080
is better to use the port name
```suggestion
    port: http
```

2024-12-18 10:56 UTC, ralgozino commented on chart/values.yaml
> +    port: 8080
```suggestion
    port: http
```

2024-12-18 11:43 UTC, viliger18 commented
Mainly our problem was that the timeout and and failure threshold were too low, initially just saved the chart and deployed with different values but saw this project is still maintained so prefer to just get the chart and change the hardcoded values of the probes

2024-12-20 18:00 UTC, ralgozino approved these changes

2024-12-20 18:03 UTC, merged

2024-12-20 18:10 UTC, ralgozino commented
Hi @viliger18 

We've released a new version of the chart with your added fields:
https://github.com/sighupio/gatekeeper-policy-manager/releases/tag/gatekeeper-policy-manager-0.13.0

Thank you for the collaboration!